
on: 
  push:
    branches:
      - release

env:
  GODOT_VERSION: 3.2.3
  GAME_PATH: .
  
jobs:
  # job id, can be anything
  export_game:

    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Create game exports
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v2

    - name: export game
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v2.6.1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
        relative_project_path: ${{ env.GAME_PATH }}
        base_version: 0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}

